name: Integration Tests

on:
  push:
    branches:
      - milestone5
  pull_request:
    branches:
      - milestone5

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies using pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests python-dotenv

      # Step 4: Load environment variables (e.g., TEST_PASSWORD)
      - name: Load environment variables
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: echo "TEST_PASSWORD=${TEST_PASSWORD}" >> $GITHUB_ENV

      # Step 5: Run integration tests
      - name: Run Integration Tests
        run: pytest --rootdir=. tests/integration/

  spin-up-backend-containers:
    name: Spin Up Backend Containers
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker and Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Verify GCP Service Account Key secret
      - name: Verify GCP SA Key
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY_CS_CRIMSONCHAT }}" ]; then
            echo "Secret GCP_SA_KEY_CS_CRIMSONCHAT is NOT accessible."
            exit 1
          else
            echo "Secret GCP_SA_KEY_CS_CRIMSONCHAT is accessible."
          fi

      # Step 4: Write GCP Service Account Key to a file
      - name: Write GCP Key File
        run: |
          echo "${{ secrets.GCP_SA_KEY_CS_CRIMSONCHAT }}" > $GITHUB_WORKSPACE/gcp_key.json

      # Step 5: Create Environment File
      # Adjust these environment variables as needed.
      - name: Create Environment File
        run: |
          echo "QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}" >> $GITHUB_WORKSPACE/.env
          echo "QDRANT_URL=${{ env.QDRANT_URL }}" >> $GITHUB_WORKSPACE/.env
          echo "QDRANT_COLLECTION_NAME=${{ env.QDRANT_COLLECTION_NAME }}" >> $GITHUB_WORKSPACE/.env
          echo "GCP_PROJECT=${{ env.GCP_PROJECT }}" >> $GITHUB_WORKSPACE/.env
          echo "LOCATION=${{ env.LOCATION }}" >> $GITHUB_WORKSPACE/.env
          echo "GCP_SERVICE_ACCOUNT=${{ env.GCP_SERVICE_ACCOUNT }}" >> $GITHUB_WORKSPACE/.env
          # Set the path to the service account credentials inside the container
          echo "GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_key.json" >> $GITHUB_WORKSPACE/.env

      - name: Debug .env File Path
        run: ls -la

      # Step 6: Start Docker containers using docker-compose
      - name: Start Backend and Frontend with Docker Compose
        run: docker-compose --env-file $GITHUB_WORKSPACE/.env up -d --build

      # Step 7: Wait for Containers
      - name: Wait for Containers to be Ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 15

      # Step 8: Check Docker Status
      - name: Check Docker Status
        run: docker ps

      # Step 9: Print Backend Logs
      - name: Print Backend Logs
        run: docker-compose logs backend

      # Step 10: Tear Down Docker Containers
      - name: Tear Down Docker Containers
        if: always()
        run: docker-compose down
